controller_list:
  - name: fake_garra_controller
    joints:
      - gripper_extension
      - left_gripper_joint
      - right_gripper_joint
initial:  # Define initial robot poses.
  - group: garra
    pose: idle