# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: garra
  joint_model_group_pose: idle
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - left_back_wheel_joint
    - left_front_wheel_joint
    - right_back_wheel_joint
    - right_front_wheel_joint
    - gripper_extension
    - left_gripper_joint
    - right_gripper_joint
    - head_swivel
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: garra_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - gripper_extension
      - left_gripper_joint
      - right_gripper_joint
gripper:
  type: velocity_controllers/JointTrajectoryController
  joints:
    - gripper_extension
    - left_gripper_joint
    - right_gripper_joint
  gains:
    gripper_extension:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_gripper_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_gripper_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1